### ISSUE TITLE
REQUEST, Make compatible with Infernal robotics next

### ISSUE THREAD

**Issue by Merlin1846** [KSP-RO/Kerbal-Joint-Reinforcement-Continued#10]
I want to use infernal robotics in rp1 but all of them are out of date/glitched except for [Infernal Robotics Next](https://forum.kerbalspaceprogram.com/index.php?/topic/184787-infernal-robotics-next/). The problem though is that it uses Kerbal Joint Reinforcement - Next not Kerbal Joint Reinforcement Continued and according to CKAN they are incompatible. I've tried running with out Kerbal Joint Reinforcement Continued but then it refuses to keep Realism.

**Comment by siimav** [comment]
Unlikely to ever happen. KJRn was specifically made for IRn so making it *compatible* might involve porting over half of the codebase.
You probably have 2 options here and I have no idea how well either of them will work:
1) Try to use Infernal RO-Robotics instead
2) Replace KJRc with KJRn

**Comment by Merlin1846** [comment]
Sorry didn't know there was that big of a difference.
