### ISSUE TITLE
EVA construction still doesn't work properly

### ISSUE THREAD

**Issue by Kaylakaze** [KSP-RO/Kerbal-Joint-Reinforcement-Continued#12]
To quote a post on the forum page (and I've experienced this issue myself):

> Interestingly this mod still breaks EVA construction completely for me. While using the default settings, as per the difficulty menu, as soon as I place a part on a ship in orbit my Kerbal essentially gets invisibly "connected" to the ship and the ship gets dragged around as the Kerbal attempts to move around while in EVA. If the kerbal is able to board the ship (such as being on a ladder while in construction mode) then there will be a phantom force that will push on the ship forever.
> 
> If I disable all the settings in the difficulty menu, then all the problems go away. So if anyone else runs across this, just disable the settings in the difficulty menu in the KJR tab before doing EVA construction.

The exact culprit seems to be the "Additional stiffening" option, at least in my testing

**Comment by siimav** [comment]
I think 4b741855b65a063fdb0a812e8c4cd9d198fc07e0 fixes it. I just made a mistake when copying the changes over from another fork. 🤦
