### ISSUE TITLE
Main Menu buttons locked.

### ISSUE THREAD

**Issue by AppleCatActual** [KSP-RO/Kerbal-Joint-Reinforcement-Continued#13]
I saw that there was one closed issue about this but no fix posted, plus its back with the latest release of KJRC. Game loads fine, no errors detected, just cant click any main menu UI, altF12 menu works fine but clearing input locks doesn't fix it. Log attached. I'll be happy to write up my modlist if needed but its long and since the problem only goes away when KJRC is removed its a good place to start.
[KSP.log](https://github.com/KSP-RO/Kerbal-Joint-Reinforcement-Continued/files/10834943/KSP.log)

**Comment by siimav** [comment]
Your install is just broken. For instance it's missing ToolbarControl which is a dependency for many mods. Also Lisas's mods are throwing a hissy fit.
IDK how having specifically KJR installed causes the main menu to lock up but it certainly won't happen with a properly working KSP install.
