### ISSUE TITLE
Is there something like this for motors?

### ISSUE THREAD

**Issue by Georodin** [KSP-RO/Kerbal-Joint-Reinforcement-Continued#6]
Is there something like this for motors?
I have the problem that I cant get things to work like they should cause the motorjoints jiggle like crazy.
especially in the wing areas where high forces apply

**Comment by siimav** [comment]
If the joints are in locked state then the latest KJR release should strengthen them significantly. If they're unlocked then unfortunately KJR isn't of any help.
