### ISSUE TITLE
Using EVA Construction causes crafts to explode

### ISSUE THREAD

**Issue by tprussak** [KSP-RO/Kerbal-Joint-Reinforcement-Continued#7]
When using the EVA construction feature that was added in 1.11 to remove a part from a craft with this mod enabled, the craft will usually explode. I believe this is because the part is not properly detached.

**Comment by Erabior** [comment]
I can concur this is happeneing

**Comment by enkido** [comment]
Same here

**Comment by siimav** [comment]
Fixed in a03d2b37110a2daaefd3a81aa9fb0dc1895a9214
