### ISSUE TITLE
Main Menu Soft Lock bug

### ISSUE THREAD

**Issue by SmallerDragons** [KSP-RO/Kerbal-Joint-Reinforcement-Continued#8]
As of 8/7/21 KJRC is soft locking the menu? I've tried it as a stand alone on stock and with other mods, but after testing seems to the the source of the issue
To recreate; install v3.5.2 Kerbal-Joint-Reinforcement-Continued, then launch game. 

Game Version 1.12.2.3167

**Comment by siimav** [comment]
Works just fine on 1.12.2 for me

**Comment by HatsumeHate** [comment]
yes, after game is loaded you cant interact with any buttons

**Comment by siimav** [comment]
Then I need a ksp.log after loading into the main menu

**Comment by HatsumeHate** [comment]
is this log located in a main folder? it works fine if you place KJR first in the load order btw

**Comment by Gordon-Dry** [comment]
Load order? Since when this is a thing in KSP world? How do you define that?

**Comment by HatsumeHate** [comment]
> Load order? Since when this is a thing in KSP world? How do you define that?

since when this game was made. ksp loads everything in the game data according to alphabetical order

**Comment by Gordon-Dry** [comment]
Yeah, ofc it does. I assumed you mean some dedicated setting for that.

**Comment by Gordon-Dry** [comment]
btw I know for sure (I quote):
`I don't suppose you did a comparison between KJR - Next and KJR - Continued? I was using the latter, and noticed a reasonable speed improvement in just removing it. I then tried KJR - Next, and I didn't seem to lose any performance (though I didn't really do proper equivalent testing and measurements). Then when encountering performance issues again I tried removing KJR - Next and did notice a slight improvement there. But not as much as when I removed KJR - Continued. But again, not good comparisons. `

My conclusion with less words
```
'Continued' - bad
'Next' - good
```

I know, this does not help with the issue. But the decision helps the user.

I have no issues with KJR Next.

**Comment by siimav** [comment]
> is this log located in a main folder? it works fine if you place KJR first in the load order btw

Yes, in the KSP root folder next to KSP_x64.exe. It can only contain relevant information if the main menu locked up as well (i.e not after you mucked around with the mod load order).

**Comment by siimav** [comment]
There's a release targeting KSP 1.12 now
