### ISSUE TITLE
In 1.12.2 version, after applying this mod , the structures of spacecrafts are very stable, but the docking ports are still as soft as rubber. 

### ISSUE THREAD

**Issue by windshear-booster** [KSP-RO/Kerbal-Joint-Reinforcement-Continued#9]

**Comment by siimav** [comment]
Well yes. KJR doesn't reinforce joints on robotic parts which technically docking ports also are since 1.12.

**Comment by windshear-booster** [comment]
Ok, thanks! This mod worked perfectly when I was playing 1.11 and I enjoyed a lot. Maybe I need to activate my brain storm to overcome this "noodle effect".

**Comment by siimav** [comment]
Fixed in d59438f4d17a3b08c57e08c0ac03c8f377bc69c7
Note that since the new KSP1.12 docking port doesn't fire onRoboticPartLockChanged event, it will stay locked forever.

**Comment by LumaLivy** [comment]
> KSP1.12 docking port doesn't fire onRoboticPartLockChanged event

I'm not familiar with writing mods but is it possible to override this behaviour and make docking ports fire the event? I'm assuming they're supposed to fire the event when toggling the rotation lock, or maybe I'm misunderstanding. I tried building a ship that relies on rotating docking ports and realized this update breaks rotation completely (the ports try to rotate and then eventually explode or snap back to their original position). 

Toggling reinforcement off in the difficulty settings window and then reloading the ship let me rotate the ports again of course but it's a bit of a hassle going back and forth every time. I downgraded to the previous version for now, not sure what to do.

**Comment by gotmachine** [comment]
> I tried building a ship that relies on rotating docking ports

Note that the stock docking port rotation feature suffer from the same issue as robotic parts : it cause all children parts of docking ports to have their pristine positions lost and set to whatever in-physics deformation is currently happening. Over the course of multiple save/load or scene switch cycles, this will cause the vessel to become more and more permanently deformed.
The only way to avoid that is to never unlock the rotation toggle and to never use that feature. I suggest using [DockRotate ](https://github.com/peteletroll/DockRotate) instead.

@siimav Added the robotics event firing on docking port lock state change, will be available in next release.

**Comment by siimav** [comment]
[Release v3.6.1](https://github.com/KSP-RO/Kerbal-Joint-Reinforcement-Continued/releases/tag/v3.6.1) now makes use of the KSPCommunityFixes patch. Thanks, @gotmachine!
